Change how grades are returned.
qwazwsx/infinite-campus pull request #13
Opened 2021-05-11 18:44 UTC by Lathryx

_Firstly_, `grades` are returned by the IC API using multiple different names, so now this library accounts for that. 

_Secondly_, the function in order to account for courses without grades was changed slightly to work with both variables as well. 

_Thirdly_, this update adds some slight restructuring to ensure users with multiple schools can still use the API (and the `comments` property was added to the returned data as well).

2021-05-11 18:55 UTC, qwazwsx requested changes
Everything looks great! However, I notice a bug in lines 308-311. If any of the `.progress` properties are nullish (i.e. 0) it will trigger the "no grades" if statement and set .grades to undefined. Another reason why nullish coalescing is great. I'll make a PR real quick and fix it.

```Javascript

// the following works
5 || undefined == 5 // !!5 == true, picks the left expression
undefined || 5 == 5 // !!undefined == false, picks the right expression

// here is the error, the || operator casts the values to booleans, and 0 is a falsy value.
0 || undefined == undefined // !!0 == false, picks the right expression


```

2021-05-11 19:08 UTC, merged

2021-05-12 14:32 UTC, Lathryx commented
> Everything looks great! However, I notice a bug in lines 308-311. If any of the `.progress` properties are nullish (i.e. 0) it will trigger the "no grades" if statement and set .grades to undefined. Another reason why nullish coalescing is great. I'll make a PR real quick and fix it.
> 
> ```js
> // the following works
> 5 || undefined == 5 // !!5 == true, picks the left expression
> undefined || 5 == 5 // !!undefined == false, picks the right expression
> 
> // here is the error, the || operator casts the values to booleans, and 0 is a falsy value.
> 0 || undefined == undefined // !!0 == false, picks the right expression
> ```
\- @qwazwsx 

Hmm, I could've sworn I fixed this with _this change:_ 
```js
// from this: 
// if (!grade.progressScore 
//        && !grade.progressPercent 
//        && !grade.progressTotalPoints 
//        && !grade.progressPointsEarned) 
//         courseResult.grades = undefined 
// to this: 
  if (!(grade.progressScore || grade.score) 
        && !(grade.progressPercent || grade.percent) 
        && !(grade.progressTotalPoints || grade.totalPoints) 
        && !(grade.progressPointsEarned || grade.pointsEarned))
            courseResult.grades = undefined;
```
This (^) is what you were talking about, correct?

2021-05-12 18:17 UTC, Lathryx commented on index.js
> +              if (grades.score === undefined || grades.percent === undefined) courseResult.grades = undefined;
@qwazwsx I see now that my change (seen above) did _not_ go through after all. 🤔

2021-05-12 18:30 UTC, qwazwsx commented on index.js
> +              if (grades.score === undefined || grades.percent === undefined) courseResult.grades = undefined;
Hmm... Okay, I see. I completely misread your commit. I thought that the if statement would trigger if *any* of the conditions were met (IE falsy value boolean behavior would apply) but I see now that isn't the case. Sorry about this, I'm re-merging your commit right now. This whole code-review thing is pretty new to me. Egg on my face :grimacing:

2021-05-12 18:34 UTC, qwazwsx commented
the documentation still needs updating to reflect the multiple schools change to `User.getCourses`
I also still need to push V3.1.0 to NPM

2021-05-12 18:50 UTC, Lathryx commented
Got it. I can help with the docs if you want. I'm eagerly waiting for the NPM update (currently working on my project's back-end, where I'll be using this API)! 

Also, send me a friend request on Discord _(Lathryx#2826)_ when you get a chance! :)

2021-05-12 21:56 UTC, Lathryx commented on index.js
> +              if (grades.score === undefined || grades.percent === undefined) courseResult.grades = undefined;
Haha! No worries at all. I'm pretty new to all this collaborative stuff too. :)